# Generated by Django 3.2.5 on 2021-07-11 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_logins'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='logins',
            table='logins',
        ),
    ]
